- hosts: all

  pre_tasks:
    - name: apt autoremove check
      become: yes 
      command: apt -y --dry-run autoremove
      register: apt_autoremove_output

    - name: print apt autoremove packages
      debug:
        msg: "{{ apt_autoremove_output.stdout_lines }}"

  tasks:    
    - name: autoremove unused packages
      become: yes
      command: apt -y autoremove
      changed_when: "'The following packages will be REMOVED' in apt_autoremove_output.stdout"

    - name: clean old packages
      become: yes
      command: apt -y clean
