- hosts: all

  tasks:
  - name: install fail2ban package
    become: true
    apt:
      name:
        - fail2ban
      update_cache: yes
  - name: create default fail2ban configuration
    become: true
    copy:
      dest: "/etc/fail2ban/jail.local"
      content: |
        ignoreip = 10.11.0.0/24
        bantime = 10m
        findtime = 10m
        maxretry = 5
        action = $(action_)s
        [sshd]
        enabled = yes
        mode    = normal
        port    = ssh
  - name: start fail2ban
    become: true
    service:
      name: fail2ban
      state: started
      enabled: yes
