- hosts: all

  tasks:
  - name: install fail2ban package
    apt:
      name:
        - fail2ban
      update_cache: yes
  - name: create default fail2ban configuration
    copy:
      dest: "/etc/fail2ban/jail.local"
      content: |
        bantime = 10m
        findtime = 10m
        maxretry = 5
        action = $(action_)s
        [sshd]
        enabled = yes
        mode    = normal
        port    = ssh
        logpath = %(sshd_log)s
        backend = %(sshd_backend)s
    become: yes
  - name: start fail2ban
    service:
      name: fail2ban
      state: started
      enabled: yes
