- hosts: all

  tasks:
  - name: install ufw package
    become: true
    apt:
      name:
        - ufw
      update_cache: yes
  - name: allow ssh in ufw
    become: true
    community.general.ufw:
      rule: allow
      port: 22
      proto: tcp
  - name: allow snmp in ufw
    become: true
    community.general.ufw:
      rule: allow
      port: 161
      proto: udp
  - name: start ufw, enable and deny by default
    become: true
    community.general.ufw:
      state: enabled
      default: deny
