- hosts: all

  tasks:
  - name: install fail2ban package
    become: true
    apt:
      name:
        - fail2ban
      update_cache: yes
  - name: set ssh backend to systemd
    become: true
    lineinfile:
      path: /etc/fail2ban/jail.conf
      regexp: '^backend = auto'
      line: backend = systemd
      backrefs: yes
  - name: create default fail2ban configuration
    become: true
    copy:
      dest: "/etc/fail2ban/jail.local"
      content: |
       [sshd]
       enabled   = true
       maxretry  = 3
       findtime  = 10m
       bantime   = 30m
       ignoreip  = 10.11.0.0/24
  - name: start fail2ban
    become: true
    service:
      name: fail2ban
      state: restarted
      enabled: yes
