- hosts: all

  become: yes
  tasks:

  - name: install core packages
    apt:
      name:
        - qemu-guest-agent
        - ssh
        - vim
        - wget
        - curl
        - iputils-ping
        - tuned
        - tuned-utils
        - telnet
        - speedtest-cli
        - netplan.io
        - tzdata
        - btop
        - python3-dnspython
        - iputils-ping
        - apt-utils
        - dialog
        - terminfo
        - kitty-terminfo
      update_cache: yes

  - name: start guest qemu-guest-agent
    service:
      name: qemu-guest-agent
      state: started
      enabled: yes
