- hosts: all

  pre_tasks:
    - name: apt remove check 
      command: apt remove -y --dry-run ubuntu-advantage-tools cloud-init
      register: apt_remove_output

    - name: print apt remove packages
      debug:
        msg: "{{ apt_remove_output.stdout_lines }}"

  tasks:    
    - name: remove unwanted packages
      become: yes
      command: apt remove -y --purge ubuntu-advantage-tools cloud-init 
      changed_when: "'The following packages will be REMOVED' in apt_remove_output.stdout"

    - name: remove configuration folders
      become: yes
      command: rm -rf /etc/cloud
