- hosts: all

  pre_tasks:
    - name: apt remove check 
      command: apt -y --dry-run remove ubuntu-advantage-tools cloud-init
      register: apt_remove_output

    - name: print apt remove packages
      debug:
        msg: "{{ apt_remove_output.stdout_lines }}"

  tasks:    
    - name: remove unused packages
      become: yes
      command: apt -y remove ubuntu-advantage-tools cloud-init 
      changed_when: "'The following packages will be REMOVED' in apt_remove_output.stdout"

    - name: remove cruft
      become: yes
      command: rm -rf /etc/cloud
