---
- hosts: all
  become: false
  tasks:
  - name: ICMP ping test to Google Public DNS via IPv4
    delegate_to: localhost
    command: ping -4 -c 2 "8.8.4.4"
    changed_when: false 
    check_mode: false
    failed_when: router_ping.rc == 1 or router_ping.rc > 2
    register: router_ping

  - name: Show Return Code
    debug:
      msg: "Successfully pinged Google Public DNS at 8.8.4.4"

  - name: ICMP ping test to DNS server via IPv6
    delegate_to: localhost
    command: ping -6 -c 2 "2001:4860:4860::8844"
    changed_when: false
    check_mode: false
    failed_when: router_ping.rc == 1 or router_ping.rc > 2
    register: router_ping

  - name: Show Return Code
    debug:
      msg: "Successfully pinged Google Public DNS at 2001:4860:4860::8844"

  - name: Look up A (IPv4) records for ipchicken.com
    ansible.builtin.debug:
      msg: "{{ query('community.dns.lookup', 'ipchicken.com.') }}"

  - name: Look up AAAA (IPv6) records for ipchicken.com
    ansible.builtin.debug:
      msg: "{{ query('community.dns.lookup', 'ipchicken.com.', type='AAAA' ) }}"
