- hosts: all

  tasks:
    - name: Test reachability to 8.8.4.4
      ansible.netcommon.net_ping:
        ansible_network_os: auto
        dest: 10.10.10.10
        count: 5
    - name: Test reachability to 1.0.0.1
      ansible.netcommon.net_ping:
        ansible_network_os: auto
        dest: 10.20.20.20
        count: 5
    - name: Test reachability to 2001:4860:4860::8844
      ansible.netcommon.net_ping:
        ansible_network_os: auto
        dest: 2001:4860:4860::8844
        count: 5
    - name: Test reachability to 2606:4700:4700::1001
      ansible.netcommon.net_ping:
        ansible_network_os: auto
        dest: 2606:4700:4700::1001
        count: 5
