- hosts: all

  become: yes
  tasks:
    # Upgrade packages
    - name: upgrade apt packages
      remote_user: administrator
      sudo: yes
      apt:
        upgrade: yes
        update_cache: yes

    # Check if reboot is required
    - name: check if system reboot is required
      remote_user: administrator
      sudo: yes
      stat:
        path: /var/run/reboot-required
      register: reboot_required
